import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils"
import Navbar from "@/components/Navbar/Navbar";
import dynamic from "next/dynamic";
const Footer = dynamic(()=> import('../components/Footer/Footer'))

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
        <body id={`pageContainer`} className={cn(
            "min-h-screen font-sans antialiased",
            inter.className + " flexColumn sc"
        )}
        >
        <Navbar/>
            {children}
        <Footer/>
        </body>
        </html>
    );
}